POST http://localhost:8000/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhyaWsuYmhvd2FsQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNTRkNzk5OTQxY2RjODVjYTg5YjMyYyIsImlhdCI6MTYzMzA2MzIxNH0.Y5LtKCAjQefvSclCtZnlTtSfdo6cuMRPV8JcRzB1V2A"
}

###

POST http://localhost:8000/auth/signup
Content-Type: application/json

{ 
    "name": "Hrik",
    "email": "hrik.bhowal@gmail.co",
    "password": "Hrik", 
    "password_confirm": "Hrik" 
}

###

DELETE http://localhost:8000/auth/logout
Content-Type: application/json

{
    "user_id": "6154d799941cdc85ca89b32c",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhyaWsuYmhvd2FsQGdtYWlsLmNvbSIsImlhdCI6MTYzMzA2MzMzNCwiZXhwIjoxNjMzMDYzMzM5fQ.395tnZ0N_fKND-6EFWw8GIn6Lx4nmmWckWgnxnHdTA8"
}\

###

POST http://localhost:8000/auth/signin
Content-Type: application/json

{ 
    "email": "hrik.bhowal@gmail.com",
    "password": "Hrik"
}

###

GET http://localhost:8000/auth/data/61639307187a61187b5e20b1

###
GET http://localhost:8000/auth/data-email/h

###
POST http://localhost:7000/api/conversations/create-chat
Content-Type: application/json

{
    "senderId": "61639307187a61187b5e20b1",
    "receiverId": "6163933a187a61187b5e20b4"
}

###

GET http://localhost:7000/api/conversations/all-conversations/61639307187a61187b5e20b1

###

POST http://localhost:7000/api/messages/send-message
Content-Type: application/json

{
    "conversationId": "616191f552806676b11ced80",
    "sender": "6154d799941cdc85ca89b32c",
    "text": "wbu"
}

###
GET http://localhost:7000/api/messages/get-message/616191f552806676b11ced80

###
GET http://localhost:7000/api/conversations/conversation-data/616191f552806676b11ced80

###
POST http://localhost:7000/api/requests/send-request
Content-Type: application/json

{
  "userId": "61639307187a61187b5e20b1",
  "userName": "h",
  "receiverEmail": "o"
}

###

GET http://localhost:7000/api/requests/get-request/6163933a187a61187b5e20b4

###
PUT http://localhost:7000/api/requests/respond/

###
GET http://localhost:7000/api/requests/friends/6163935d187a61187b5e20b7
