POST http://localhost:8000/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhyaWsuYmhvd2FsQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNTRkNzk5OTQxY2RjODVjYTg5YjMyYyIsImlhdCI6MTYzMzA2MzIxNH0.Y5LtKCAjQefvSclCtZnlTtSfdo6cuMRPV8JcRzB1V2A"
}

###

POST http://localhost:8000/auth/signup
Content-Type: application/json

{ 
    "name": "Hrik",
    "email": "hrik.bhowal@gmail.co",
    "password": "Hrik", 
    "password_confirm": "Hrik" 
}

###

DELETE http://localhost:8000/auth/logout
Content-Type: application/json

{
    "user_id": "6154d799941cdc85ca89b32c",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhyaWsuYmhvd2FsQGdtYWlsLmNvbSIsImlhdCI6MTYzMzA2MzMzNCwiZXhwIjoxNjMzMDYzMzM5fQ.395tnZ0N_fKND-6EFWw8GIn6Lx4nmmWckWgnxnHdTA8"
}\

###

POST http://localhost:8000/auth/signin
Content-Type: application/json

{ 
    "email": "hrik.bhowal@gmail.com",
    "password": "Hrik"
}

###
POST http://localhost:7000/api/conversation/create-chats
Content-Type: application/json

{
    "senderId": "6154d799941cdc85ca89b32c",
    "receiverId": "6154da8f9b5b8cd13c58c59e"
}

###

GET http://localhost:7000/api/conversations/data/6157db28cc12e6cc02b57de4

###

POST http://localhost:7000/api/messages/send-message
Content-Type: application/json

{
    "conversationId": "6160f0be4be65d1218fb0d0e",
    "sender": "6154da8f9b5b8cd13c58c59e",
    "text": "Ok Bye"
}

###
