POST http://localhost:8000/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTY5MDQ0ZTVhODFkYjVhODlkODhjZjUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpYXQiOjE2MzQ4NTM2MTIsImV4cCI6MTY2NjQxMTIxMn0.9bJ9x1B-eWjyRPhLvRReuyj6HJfEbTwbEEhFLoR90M4"
}

###

POST http://localhost:8000/auth/signup
Content-Type: application/json

{ 
    "first_name": "a",
    "last_name": "a",
    "email": "hrik.bhowal@gmail.com",
    "password": "aaaaaaaa", 
    "password_confirm": "aaaaaaaa" 
}

###

DELETE http://localhost:8000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTY4MjUyNzM2ZjU5ZDY1YWI2MTY1MGYiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpYXQiOjE2MzQyNTkxNDgsImV4cCI6MTY2NTgxNjc0OH0.6vTGP3Vo_MH1eetH8QU8Vk4h_mycsNL_jBpCrvN7PtE"
}

###

POST http://localhost:8000/auth/signin
Content-Type: application/json

{ 
    "email": "hrik.bhowal@gmail.com",
    "password": "f"
}

###

###
GET http://localhost:7000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTY4MjUyNzM2ZjU5ZDY1YWI2MTY1MGYiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpYXQiOjE2MzQyMjMxNjEsImV4cCI6MTYzNDIyMzE3Nn0.6iOEyohxljEAsgCj1wQiH82J_HEErIAp14JqUU_86O0
###

GET http://localhost:7000/api/user/user-id/61730b08b41a3c7787d10edd

###
GET http://localhost:8000/auth/data-email/h

###
POST http://localhost:7000/api/conversations/create-chat
Content-Type: application/json

{
    "senderId": "6163933a187a61187b5e20b4",
    "receiverId": "61639307187a61187b5e20b1"
}

###

GET http://localhost:7000/api/conversations/all-conversations/61639307187a61187b5e20b1

###

POST http://localhost:7000/api/messages/send-message
Content-Type: application/json

{
    "conversationId": "616191f552806676b11ced80",
    "sender": "6154d799941cdc85ca89b32c",
    "text": "wbu"
}

###
GET http://localhost:7000/api/messages/get-message/616191f552806676b11ced80

###
GET http://localhost:7000/api/conversations/conversation-data/61730b08b41a3c7787d10edd

###
GET http://localhost:7000/api/images/61930933adacba91eb2afe45

###
POST http://localhost:7000/api/requests/send-request
Content-Type: application/json

{
  "userId": "61730b08b41a3c7787d10edd",
  "userName": "borispopov10@yahoo.com",
  "receiverEmail": "hrik.bhowal@gmail.com"
}

###

GET http://localhost:7000/api/requests/get-request/6163933a187a61187b5e20b4

###
PUT http://localhost:7000/api/requests/respond/

###
GET http://localhost:7000/api/requests/friends/61639307187a61187b5e20b1

###
PUT http://localhost:7000/api/user/update-profile/first-name
Content-Type: application/json

{
    "userId": "617c40aa0cc7aeca24fc9f81",
    "firstName": ""
}

###
PUT http://localhost:7000/api/requests/remove
Content-Type: application/json

{
    "removerId": "617c40aa0cc7aeca24fc9f81",
    "toRemoveId": "61834d99d229d18317176be3" 
}